from typing import Any, Dict, List

from github.GithubObject import CompletableGithubObject

class RepositoryLicense(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def node_id(self) -> str: ...
    @property
    def spdx_id(self) -> str: ...
    @property
    def url(self) -> str: ...
